### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by adeoti-ade** [marlanperumal/pdf_statement_reader#11]
TypeError: join() missing 1 required positional argument: 'path'

**Comment by marlanperumal** [comment]
That's not a particularly useful error :) can you provide steps to reproduce?

**Comment by Huntarhio** [comment]
Traceback (most recent call last):
  File "c:\users\credpal\anaconda3\lib\runpy.py", line 193, in
_run_module_as_main
    "__main__", mod_spec)
  File "c:\users\credpal\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Credpal\Anaconda3\Scripts\psr.exe\__main__.py", line 9, in
<module>
  File "c:\users\credpal\anaconda3\lib\site-packages\click\core.py", line
764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\credpal\anaconda3\lib\site-packages\click\core.py", line
717, in main
    rv = self.invoke(ctx)
  File "c:\users\credpal\anaconda3\lib\site-packages\click\core.py", line
1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\credpal\anaconda3\lib\site-packages\click\core.py", line
956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\credpal\anaconda3\lib\site-packages\click\core.py", line
555, in invoke
    return callback(*args, **kwargs)
  File
"c:\users\credpal\anaconda3\lib\site-packages\pdf_statement_reader\__init__.py",
line 75, in pdf2csv
    config = load_config(config_spec)
  File
"c:\users\credpal\anaconda3\lib\site-packages\pdf_statement_reader\__init__.py",
line 37, in load_config
    config_dir = os.path.join(*config_spec.split(".")[:-1])
TypeError: join() missing 1 required positional argument: 'path'

**Comment by Huntarhio** [comment]
psr pdf2csv -config C:/Users/Credpal/ACCESS.pdf C:/Users/Credpal/ACCESS.pdf.csv

**Comment by flywire** [comment]
No feedback. Add https://docs.python.org/3/howto/logging.html
