### ISSUE TITLE
issue with test pdf file

### ISSUE THREAD

**Issue by kiashann** [marlanperumal/pdf_statement_reader#60]
Hi. I installed the library on Google Colab and I ran the below instruction but I got the following error. 

!psr pdf2csv '/content/bank-statement.pdf'

How can I use it in python code?
Error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Debit Amount'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/psr", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pdf_statement_reader/__init__.py", line 80, in pdf2csv
    df = parse_statement(input_filename, config)
  File "/usr/local/lib/python3.10/dist-packages/pdf_statement_reader/parse.py", line 104, in parse_statement
    clean_numeric(statement, config)
  File "/usr/local/lib/python3.10/dist-packages/pdf_statement_reader/parse.py", line 50, in clean_numeric
    df[col] = df[col].apply(format_negatives)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'Debit Amount'

**Comment by marlanperumal** [comment]
Is this still an issue? I've updated the project (including migrating to uv for python and package management) and fixed a couple bugs along the way.  My assumption on the error you were getting before is that the headings weren't getting picked up in the targeted area. The current version should deal with that properly now.

I'm picking up this project again after a bit of a hiatus. If I don't see any response on this issue within 2 weeks, it will be closed, so that only current issues will be present and can be addressed.
